export const defaultAQ = {
  content: {
    hero: {
      eyebrow: "Authority Quotient",
      title: "How much authority do you",
      accent: "command in the room?",
      description:
        "Authority Quotient (AQ) is CCC for Leaders' framework for understanding how much authority a leader actually commands in a room — and how to raise it.",
      secondary:
        "You may have the expertise, experience and ideas. But how effectively does that expertise translate into influence?",
      button: "Discover My AQ",
    },
    overview: {
      eyebrow: "What is Authority Quotient?",
      heading: "Expertise is valuable.",
      accent: "Authority determines how it lands.",
      body: "Authority Quotient looks at the way a leader's contribution is experienced in the room. It gives leaders a framework for understanding their current Authority Quotient and identifying opportunities to strengthen it.",
    },
    why: {
      eyebrow: "Why AQ matters",
      heading: "You can know the answer and",
      accent: "still struggle to move the room.",
      body: "A leader's expertise is only part of the equation. The way you communicate, contribute and engage with others can affect how your expertise is received. AQ gives leaders a way to examine that gap. It can help you think about:",
      points: [
        "How your ideas are received",
        "How you contribute in important conversations",
        "How effectively you communicate your thinking",
        "How your expertise translates into influence",
        "Where your leadership authority can be strengthened",
      ],
    },
    assessment: {
      eyebrow: "Discover your AQ",
      heading: "Discover your",
      accent: "Authority Quotient",
      duration: "Complete the assessment at your own pace",
      body: "Answer questions based on how you typically respond in workplace situations. Your answers are used to calculate your score and generate an AQ profile.",
      steps: [
        { title: "Answer", text: "Choose the response that best reflects how you typically act." },
        { title: "Discover", text: "Receive your AQ score and profile." },
        { title: "Understand", text: "Explore the strengths and areas to watch associated with your profile." },
        { title: "Take the next step", text: "Explore relevant CCC resources or start a conversation." },
      ],
      button: "Find My AQ Score",
    },
    profile: {
      eyebrow: "Your AQ Profile",
      heading: "More than",
      accent: "a score",
      body: "Your AQ result includes a profile designed to give you a more useful picture of how your authority shows up.",
      fields: ["Profile name", "Headline", "Description", "Strengths", "Watch-outs", "Recommended CCC service"],
      exampleLabel: "About your result",
      exampleHeadline: "A clearer picture of your authority",
      exampleDescription: "Your profile will explain how your answers connect to your strengths and opportunities for growth.",
      exampleNote: "",
    },
    leadership: {
      eyebrow: "AQ and Leadership",
      heading: "Authority is",
      accent: "experienced, not simply assigned.",
      body: "Job title can give someone formal authority. AQ is concerned with the authority a leader actually commands in the room — that distinction is central to CCC's positioning.",
      secondary: "AQ can be applied to different leadership situations and communication styles.",
    },
    workplace: {
      eyebrow: "AQ in the Workplace",
      heading: "Where does",
      accent: "Authority Quotient matter?",
      body: "You can connect AQ to situations leaders encounter every day.",
      situations: [
        { title: "Meetings", text: "How effectively do your contributions influence the conversation?", icon: "UsersRound" },
        { title: "Presentations", text: "How does your expertise translate into a message people remember?", icon: "Presentation" },
        { title: "Difficult conversations", text: "How do you communicate when the stakes are high?", icon: "MessageSquareWarning" },
        { title: "Team interactions", text: "How do people respond to your leadership and ideas?", icon: "Users" },
        { title: "Client conversations", text: "How effectively do you establish credibility and influence?", icon: "Handshake" },
      ],
    },
    action: {
      eyebrow: "From AQ to Action",
      heading: "Knowing your AQ is",
      accent: "the starting point.",
      body: "The assessment is designed to introduce people to the framework. For organisations that want to go further, CCC can connect AQ insights with its existing interventions:",
      services: [],
      button: "Explore Our Services",
    },
    finalCta: {
      heading: "What is your",
      accent: "Authority Quotient?",
      body: "Take the AQ assessment and get a clearer starting point for your leadership development.",
      button: "Discover My AQ",
    },
  },
  questions: [],
  profiles: [],
};
